export const GENELEDGER_ABI = {
  address: "0x8e82cae5ef915df0a3406cf36777da0b13418a453b97267696cf660f044b51cf",
  name: "GeneLedger",
  friends: [],
  exposed_functions: [
    {
      name: "entry_exists",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "exists_address_list",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["bool"],
    },
    {
      name: "get_addresses",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["vector<address>"],
    },
    {
      name: "get_entry",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<u8>", "vector<vector<u8>>", "u64"],
    },
    {
      name: "post_address",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "store_entry",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>", "vector<vector<u8>>", "u64"],
      return: [],
    },
  ],
  structs: [
    {
      name: "Entry",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        { name: "merkle_root", type: "vector<u8>" },
        { name: "date", type: "u64" },
        { name: "snp_hashes", type: "vector<vector<u8>>" },
        { name: "called", type: "bool" },
      ],
    },
    {
      name: "AddressList",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "addresses", type: "vector<address>" }],
    },
    {
      name: "BoardObjectController",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "extend_ref", type: "0x1::object::ExtendRef" }],
    },
  ],
} as const;
